[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "crosslinked_mfp_analysis"
authors = [{name = "Jacob Graham", email = "jacobgraham2025@u.northwestern.edu"}]
dynamic = ["version", "description"]
